AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  actual-leave-abhijeet

  Sample SAM Template for actual-leave-abhijeet

Parameters:
  JwtSecret:
    Type: String
    Description: JWT Secret for token authorization
    NoEcho: true

Globals:
  Function:
    Timeout: 15
    LoggingConfig:
      LogFormat: JSON

Resources:
  LeaveTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: LeaveApprovalAbhijeet
      AttributeDefinitions:
        - AttributeName: requestId
          AttributeType: S
      KeySchema:
        - AttributeName: requestId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
  

  LeaveAPI:
    Type: AWS::Serverless::Api
    Properties:
      Name: LeaveManagementAPI
      StageName: Prod
      Cors: "'*'"
      Auth:
        DefaultAuthorizer: TokenAuthorizer
        Authorizers:
          TokenAuthorizer:
            FunctionArn: !GetAtt AuthorizerFunction.Arn
            Identity:
              Header: Authorization
              ValidationExpression: "^Bearer [-0-9a-zA-Z._]*$"
  AuthorizerFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints:
          - authorizer.ts
    Properties:
      CodeUri: hello-world/
      Handler: authorizer.handler
      Runtime: nodejs22.x
      Architectures:
        - x86_64
      Policies:
        - Statement:
            
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource: "*"
      Environment:
        Variables:
          JWT_SECRET: !Ref JwtSecret

  SubmitLeaveFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints:
          - app.ts
    Properties:
      CodeUri: hello-world/
      Handler: app.applyLeave
      Runtime: nodejs22.x
      Architectures:
        - x86_64
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref LeaveTable
       
        - Statement:
            - Effect: Allow
              Action:
                - states:StartExecution
              Resource: !Ref LeaveStateMachine
      Environment:
        Variables:
          TABLE_NAME: !Ref LeaveTable
          SES_EMAIL: "abhijeet.aayush@antstack.io"
          STATE_MACHINE_ARN: !Ref LeaveStateMachine
          APPROVER_EMAIL: "abhijeet.aayush@antstack.io"
          JWT_SECRET: !Ref JwtSecret
      Events:
        ApplyLeave:
          Type: Api
          Properties:
            Path: /apply-leave
            Method: POST
            RestApiId: !Ref LeaveAPI
            Auth:
              Authorizer: TokenAuthorizer

  SendApprovalEmailFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints:
          - app.ts
    Properties:
      CodeUri: hello-world/
      Handler: app.sendApprovalEmail
      Runtime: nodejs22.x
      Architectures:
        - x86_64
      Policies:
        - AmazonSESFullAccess
      Environment:
        Variables:
          SES_EMAIL: "abhijeet.aayush@antstack.io"
          APPROVER_EMAIL: "abhijeet.aayush@antstack.io"

  ProcessApprovalFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints:
          - app.ts
    Properties:
      CodeUri: hello-world/
      Handler: app.processApproval
      Runtime: nodejs22.x
      Architectures:
        - x86_64
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - states:SendTaskSuccess
                - states:SendTaskFailure
              Resource: "*"
      Environment:
        Variables:
          JWT_SECRET: !Ref JwtSecret
      Events:
        ProcessApproval:
          Type: Api
          Properties:
            Path: /process-approval
            Method: GET
            RestApiId: !Ref LeaveAPI
            Auth:
              Authorizer: NONE

  NotifyUserFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints:
          - app.ts
    Properties:
      CodeUri: hello-world/
      Handler: app.notifyUser
      Runtime: nodejs22.x
      Architectures:
        - x86_64
      Policies:
        - AmazonSESFullAccess
      Environment:
        Variables:
          SES_EMAIL: "abhijeet.aayush@antstack.io"
          APPROVER_EMAIL: "abhijeet.aayush@antstack.io"

  LeaveStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      DefinitionUri: step-function.asl.json
      DefinitionSubstitutions:
        SendApprovalEmailFunctionArn: !GetAtt SendApprovalEmailFunction.Arn
        NotifyUserFunctionArn: !GetAtt NotifyUserFunction.Arn
      Policies:
        - LambdaInvokePolicy:
            FunctionName: !Ref SendApprovalEmailFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref NotifyUserFunction
  